// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: proto/chronos/v1/worker.proto

package chronosv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // builtin | webhook
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Attempt       int32                  `protobuf:"varint,6,opt,name=attempt,proto3" json:"attempt,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,7,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	TraceId       string                 `protobuf:"bytes,8,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteJobRequest) Reset() {
	*x = ExecuteJobRequest{}
	mi := &file_proto_chronos_v1_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteJobRequest) ProtoMessage() {}

func (x *ExecuteJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chronos_v1_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteJobRequest.ProtoReflect.Descriptor instead.
func (*ExecuteJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_chronos_v1_worker_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ExecuteJobRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecuteJobRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExecuteJobRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ExecuteJobRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecuteJobRequest) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *ExecuteJobRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *ExecuteJobRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ExecuteJobRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ExecuteJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteJobResponse) Reset() {
	*x = ExecuteJobResponse{}
	mi := &file_proto_chronos_v1_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteJobResponse) ProtoMessage() {}

func (x *ExecuteJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chronos_v1_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteJobResponse.ProtoReflect.Descriptor instead.
func (*ExecuteJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_chronos_v1_worker_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteJobResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ExecuteJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CancelJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobRequest) Reset() {
	*x = CancelJobRequest{}
	mi := &file_proto_chronos_v1_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobRequest) ProtoMessage() {}

func (x *CancelJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chronos_v1_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobRequest.ProtoReflect.Descriptor instead.
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_chronos_v1_worker_proto_rawDescGZIP(), []int{2}
}

func (x *CancelJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CancelJobRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type CancelJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cancelled     bool                   `protobuf:"varint,1,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobResponse) Reset() {
	*x = CancelJobResponse{}
	mi := &file_proto_chronos_v1_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobResponse) ProtoMessage() {}

func (x *CancelJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chronos_v1_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobResponse.ProtoReflect.Descriptor instead.
func (*CancelJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_chronos_v1_worker_proto_rawDescGZIP(), []int{3}
}

func (x *CancelJobResponse) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_chronos_v1_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chronos_v1_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_chronos_v1_worker_proto_rawDescGZIP(), []int{4}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Capacity      int32                  `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	ActiveJobs    int32                  `protobuf:"varint,3,opt,name=active_jobs,json=activeJobs,proto3" json:"active_jobs,omitempty"`
	Healthy       bool                   `protobuf:"varint,4,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_chronos_v1_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chronos_v1_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_chronos_v1_worker_proto_rawDescGZIP(), []int{5}
}

func (x *HealthResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HealthResponse) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *HealthResponse) GetActiveJobs() int32 {
	if x != nil {
		return x.ActiveJobs
	}
	return 0
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // host:port for WorkerService
	Capacity      int32                  `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	CapBuiltin    bool                   `protobuf:"varint,4,opt,name=cap_builtin,json=capBuiltin,proto3" json:"cap_builtin,omitempty"`
	CapWebhook    bool                   `protobuf:"varint,5,opt,name=cap_webhook,json=capWebhook,proto3" json:"cap_webhook,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Token         string                 `protobuf:"bytes,7,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_chronos_v1_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chronos_v1_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_chronos_v1_worker_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *RegisterRequest) GetCapBuiltin() bool {
	if x != nil {
		return x.CapBuiltin
	}
	return false
}

func (x *RegisterRequest) GetCapWebhook() bool {
	if x != nil {
		return x.CapWebhook
	}
	return false
}

func (x *RegisterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RegisterRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_chronos_v1_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chronos_v1_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_chronos_v1_worker_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	ActiveJobs    int32                  `protobuf:"varint,2,opt,name=active_jobs,json=activeJobs,proto3" json:"active_jobs,omitempty"`
	Capacity      int32                  `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_chronos_v1_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chronos_v1_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_chronos_v1_worker_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetActiveJobs() int32 {
	if x != nil {
		return x.ActiveJobs
	}
	return 0
}

func (x *HeartbeatRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *HeartbeatRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	CancelJobIds  []string               `protobuf:"bytes,2,rep,name=cancel_job_ids,json=cancelJobIds,proto3" json:"cancel_job_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_chronos_v1_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chronos_v1_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_chronos_v1_worker_proto_rawDescGZIP(), []int{9}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HeartbeatResponse) GetCancelJobIds() []string {
	if x != nil {
		return x.CancelJobIds
	}
	return nil
}

type DeregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterRequest) Reset() {
	*x = DeregisterRequest{}
	mi := &file_proto_chronos_v1_worker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRequest) ProtoMessage() {}

func (x *DeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chronos_v1_worker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRequest.ProtoReflect.Descriptor instead.
func (*DeregisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_chronos_v1_worker_proto_rawDescGZIP(), []int{10}
}

func (x *DeregisterRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *DeregisterRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type DeregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterResponse) Reset() {
	*x = DeregisterResponse{}
	mi := &file_proto_chronos_v1_worker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterResponse) ProtoMessage() {}

func (x *DeregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chronos_v1_worker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterResponse.ProtoReflect.Descriptor instead.
func (*DeregisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_chronos_v1_worker_proto_rawDescGZIP(), []int{11}
}

func (x *DeregisterResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ReportResultRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	JobId       string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ExecutionId string                 `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	WorkerId    string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Attempt     int32                  `protobuf:"varint,4,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Success     bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	Output      []byte                 `protobuf:"bytes,6,opt,name=output,proto3" json:"output,omitempty"`
	Error       string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	Retryable   bool                   `protobuf:"varint,8,opt,name=retryable,proto3" json:"retryable,omitempty"`
	DurationMs  int64                  `protobuf:"varint,9,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Token       string                 `protobuf:"bytes,10,opt,name=token,proto3" json:"token,omitempty"`
	// reason: success | failed | timeout | cancelled
	Reason        string `protobuf:"bytes,11,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultRequest) Reset() {
	*x = ReportResultRequest{}
	mi := &file_proto_chronos_v1_worker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultRequest) ProtoMessage() {}

func (x *ReportResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chronos_v1_worker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultRequest.ProtoReflect.Descriptor instead.
func (*ReportResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_chronos_v1_worker_proto_rawDescGZIP(), []int{12}
}

func (x *ReportResultRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ReportResultRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ReportResultRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *ReportResultRequest) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *ReportResultRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportResultRequest) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ReportResultRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReportResultRequest) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *ReportResultRequest) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ReportResultRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ReportResultRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReportResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultResponse) Reset() {
	*x = ReportResultResponse{}
	mi := &file_proto_chronos_v1_worker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultResponse) ProtoMessage() {}

func (x *ReportResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chronos_v1_worker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultResponse.ProtoReflect.Descriptor instead.
func (*ReportResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_chronos_v1_worker_proto_rawDescGZIP(), []int{13}
}

func (x *ReportResultResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_proto_chronos_v1_worker_proto protoreflect.FileDescriptor

const file_proto_chronos_v1_worker_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/chronos/v1/worker.proto\x12\n" +
	"chronos.v1\"\xe9\x02\n" +
	"\x11ExecuteJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\tR\vexecutionId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12\x18\n" +
	"\aattempt\x18\x06 \x01(\x05R\aattempt\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\a \x01(\x03R\ttimeoutMs\x12\x19\n" +
	"\btrace_id\x18\b \x01(\tR\atraceId\x12G\n" +
	"\bmetadata\x18\t \x03(\v2+.chronos.v1.ExecuteJobRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"J\n" +
	"\x12ExecuteJobResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"L\n" +
	"\x10CancelJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\tR\vexecutionId\"1\n" +
	"\x11CancelJobResponse\x12\x1c\n" +
	"\tcancelled\x18\x01 \x01(\bR\tcancelled\"\x0f\n" +
	"\rHealthRequest\"\x84\x01\n" +
	"\x0eHealthResponse\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1a\n" +
	"\bcapacity\x18\x02 \x01(\x05R\bcapacity\x12\x1f\n" +
	"\vactive_jobs\x18\x03 \x01(\x05R\n" +
	"activeJobs\x12\x18\n" +
	"\ahealthy\x18\x04 \x01(\bR\ahealthy\"\xb8\x02\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\x05R\bcapacity\x12\x1f\n" +
	"\vcap_builtin\x18\x04 \x01(\bR\n" +
	"capBuiltin\x12\x1f\n" +
	"\vcap_webhook\x18\x05 \x01(\bR\n" +
	"capWebhook\x12?\n" +
	"\x06labels\x18\x06 \x03(\v2'.chronos.v1.RegisterRequest.LabelsEntryR\x06labels\x12\x14\n" +
	"\x05token\x18\a \x01(\tR\x05token\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"<\n" +
	"\x10RegisterResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x82\x01\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1f\n" +
	"\vactive_jobs\x18\x02 \x01(\x05R\n" +
	"activeJobs\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\x05R\bcapacity\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\"I\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12$\n" +
	"\x0ecancel_job_ids\x18\x02 \x03(\tR\fcancelJobIds\"F\n" +
	"\x11DeregisterRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"$\n" +
	"\x12DeregisterResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\xbb\x02\n" +
	"\x13ReportResultRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\tR\vexecutionId\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x12\x18\n" +
	"\aattempt\x18\x04 \x01(\x05R\aattempt\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x06 \x01(\fR\x06output\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12\x1c\n" +
	"\tretryable\x18\b \x01(\bR\tretryable\x12\x1f\n" +
	"\vduration_ms\x18\t \x01(\x03R\n" +
	"durationMs\x12\x14\n" +
	"\x05token\x18\n" +
	" \x01(\tR\x05token\x12\x16\n" +
	"\x06reason\x18\v \x01(\tR\x06reason\"&\n" +
	"\x14ReportResultResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xe7\x01\n" +
	"\rWorkerService\x12K\n" +
	"\n" +
	"ExecuteJob\x12\x1d.chronos.v1.ExecuteJobRequest\x1a\x1e.chronos.v1.ExecuteJobResponse\x12H\n" +
	"\tCancelJob\x12\x1c.chronos.v1.CancelJobRequest\x1a\x1d.chronos.v1.CancelJobResponse\x12?\n" +
	"\x06Health\x12\x19.chronos.v1.HealthRequest\x1a\x1a.chronos.v1.HealthResponse2\xc3\x02\n" +
	"\x10SchedulerService\x12E\n" +
	"\bRegister\x12\x1b.chronos.v1.RegisterRequest\x1a\x1c.chronos.v1.RegisterResponse\x12H\n" +
	"\tHeartbeat\x12\x1c.chronos.v1.HeartbeatRequest\x1a\x1d.chronos.v1.HeartbeatResponse\x12K\n" +
	"\n" +
	"Deregister\x12\x1d.chronos.v1.DeregisterRequest\x1a\x1e.chronos.v1.DeregisterResponse\x12Q\n" +
	"\fReportResult\x12\x1f.chronos.v1.ReportResultRequest\x1a .chronos.v1.ReportResultResponseBAZ?github.com/ghrushneshr25/chronos-dev/proto/chronos/v1;chronosv1b\x06proto3"

var (
	file_proto_chronos_v1_worker_proto_rawDescOnce sync.Once
	file_proto_chronos_v1_worker_proto_rawDescData []byte
)

func file_proto_chronos_v1_worker_proto_rawDescGZIP() []byte {
	file_proto_chronos_v1_worker_proto_rawDescOnce.Do(func() {
		file_proto_chronos_v1_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_chronos_v1_worker_proto_rawDesc), len(file_proto_chronos_v1_worker_proto_rawDesc)))
	})
	return file_proto_chronos_v1_worker_proto_rawDescData
}

var file_proto_chronos_v1_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_chronos_v1_worker_proto_goTypes = []any{
	(*ExecuteJobRequest)(nil),    // 0: chronos.v1.ExecuteJobRequest
	(*ExecuteJobResponse)(nil),   // 1: chronos.v1.ExecuteJobResponse
	(*CancelJobRequest)(nil),     // 2: chronos.v1.CancelJobRequest
	(*CancelJobResponse)(nil),    // 3: chronos.v1.CancelJobResponse
	(*HealthRequest)(nil),        // 4: chronos.v1.HealthRequest
	(*HealthResponse)(nil),       // 5: chronos.v1.HealthResponse
	(*RegisterRequest)(nil),      // 6: chronos.v1.RegisterRequest
	(*RegisterResponse)(nil),     // 7: chronos.v1.RegisterResponse
	(*HeartbeatRequest)(nil),     // 8: chronos.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),    // 9: chronos.v1.HeartbeatResponse
	(*DeregisterRequest)(nil),    // 10: chronos.v1.DeregisterRequest
	(*DeregisterResponse)(nil),   // 11: chronos.v1.DeregisterResponse
	(*ReportResultRequest)(nil),  // 12: chronos.v1.ReportResultRequest
	(*ReportResultResponse)(nil), // 13: chronos.v1.ReportResultResponse
	nil,                          // 14: chronos.v1.ExecuteJobRequest.MetadataEntry
	nil,                          // 15: chronos.v1.RegisterRequest.LabelsEntry
}
var file_proto_chronos_v1_worker_proto_depIdxs = []int32{
	14, // 0: chronos.v1.ExecuteJobRequest.metadata:type_name -> chronos.v1.ExecuteJobRequest.MetadataEntry
	15, // 1: chronos.v1.RegisterRequest.labels:type_name -> chronos.v1.RegisterRequest.LabelsEntry
	0,  // 2: chronos.v1.WorkerService.ExecuteJob:input_type -> chronos.v1.ExecuteJobRequest
	2,  // 3: chronos.v1.WorkerService.CancelJob:input_type -> chronos.v1.CancelJobRequest
	4,  // 4: chronos.v1.WorkerService.Health:input_type -> chronos.v1.HealthRequest
	6,  // 5: chronos.v1.SchedulerService.Register:input_type -> chronos.v1.RegisterRequest
	8,  // 6: chronos.v1.SchedulerService.Heartbeat:input_type -> chronos.v1.HeartbeatRequest
	10, // 7: chronos.v1.SchedulerService.Deregister:input_type -> chronos.v1.DeregisterRequest
	12, // 8: chronos.v1.SchedulerService.ReportResult:input_type -> chronos.v1.ReportResultRequest
	1,  // 9: chronos.v1.WorkerService.ExecuteJob:output_type -> chronos.v1.ExecuteJobResponse
	3,  // 10: chronos.v1.WorkerService.CancelJob:output_type -> chronos.v1.CancelJobResponse
	5,  // 11: chronos.v1.WorkerService.Health:output_type -> chronos.v1.HealthResponse
	7,  // 12: chronos.v1.SchedulerService.Register:output_type -> chronos.v1.RegisterResponse
	9,  // 13: chronos.v1.SchedulerService.Heartbeat:output_type -> chronos.v1.HeartbeatResponse
	11, // 14: chronos.v1.SchedulerService.Deregister:output_type -> chronos.v1.DeregisterResponse
	13, // 15: chronos.v1.SchedulerService.ReportResult:output_type -> chronos.v1.ReportResultResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_chronos_v1_worker_proto_init() }
func file_proto_chronos_v1_worker_proto_init() {
	if File_proto_chronos_v1_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_chronos_v1_worker_proto_rawDesc), len(file_proto_chronos_v1_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_chronos_v1_worker_proto_goTypes,
		DependencyIndexes: file_proto_chronos_v1_worker_proto_depIdxs,
		MessageInfos:      file_proto_chronos_v1_worker_proto_msgTypes,
	}.Build()
	File_proto_chronos_v1_worker_proto = out.File
	file_proto_chronos_v1_worker_proto_goTypes = nil
	file_proto_chronos_v1_worker_proto_depIdxs = nil
}
